---

# This job template can be used to assume a role against AWS
# Note: image used in the job extending this template requires `curl` to be present
# It will require input:
# - ARS_AWS_PROFILE: the central profile name used for config/credentials
# - ARS_ROLE_TO_ASSUME: full ARN of the AWS Role to assume
#
# The template will export the resulting short lived session credentials in the environment
#
# The job template is ment to be included and extended as part of another job
# eg.:
#  include:
#    - project: automation/cicd/templates
#      ref: ${project latest version}
#      file: jobs/utils/aws-assume-role.gitlab-ci.yml
#  job1:
#    extends:
#      - .aws_assume_role
#    variables:
#      ARS_AWS_PROFILE: "<team>-<aws env>"
#      ARS_AWS_ROLE_TO_ASSUME: "arn:aws:iam:<id>:role/<role_name>"
#    script:
#      - # Do Something against AWS
#      - /bin/true

.aws_assume_role:
  variables:
    ARS_AWS_PROFILE: ""
    ARS_AWS_ROLE_TO_ASSUME: ""
    ARS_PAYLOAD: "{\"role-to-assume\":\"${ARS_AWS_ROLE_TO_ASSUME}\",\"ci-job-token\":\"${CI_JOB_TOKEN}\",\"aws-profile\":\"${ARS_AWS_PROFILE}\"}"
    ARS_ENDPOINT: 'http://nomad.dev.yelo.inet.telenet.be/ars/assumerole'
  before_script:
    - curl -XPOST -s "${ARS_ENDPOINT}" -H 'Content-Type:application/json' -d "${ARS_PAYLOAD}" -o .env
    - export $(cat .env | xargs)

...
