---

include: gitlab-http-access.gitlab-ci.yml

stages:
  - release

.semantic-release:
  extends:
    - .gitlab_http_access
  image: $REGISTRY/semantic-release:v1.1.0
  stage: release
  script:
    - GL_TOKEN=${SEMANTICRELEASE_TOKEN} semantic-release --debug --extends @enttribe/semantic-release-config --repository-url "${GITLAB_AUTHENTICATED_REPO_URL}"
  rules:
    - if: $CI_DEFAULT_BRANCH == $CI_COMMIT_BRANCH

...
