---

include: gitlab-http-access.gitlab-ci.yml

# Use this job template to provide automated samentic version tags and gitlab releases
# for you projects
#
# Use this job template by including this file from the project
# and defining the release stage
#
# eg.:
# include:
#   - project: automation/cicd/templates
#     version: ${latest project release version}
#     file: semantic-release.gitlab-ci.yml
# stages:
#   - release

semantic-release:
  extends:
    - .gitlab_http_access
  variables:
    SEMANTIC_RELEASE_USER: semantic-release-bot
    SEMANTIC_RELEASE_AUTH: ${SEMANTICRELEASE_TOKEN}
    GITLAB_USERNAME: ${SEMANTIC_RELEASE_USER}
    GITLAB_USERAUTH: ${SEMANTIC_RELEASE_AUTH}
  image: $REGISTRY/semantic-release:v1.3.16@sha256:cfa085af679aa6557213c4dc5b5373a13cbabd14bf5670b873ee4418d2897e0c
  stage: release
  script:
    - GL_TOKEN=${SEMANTICRELEASE_TOKEN} semantic-release --extends @enttribe/semantic-release-config --repository-url "${GITLAB_AUTHENTICATED_REPO_URL}"
  rules:
    - if: $CI_DEFAULT_BRANCH == $CI_COMMIT_BRANCH

...
