---

include: gitlab-http-access.gitlab-ci.yml

stages:
  - release

.semantic-release:
  extends:
    - .gitlab_http_access
  image: $REGISTRY/semantic-release:v1.1.0
  stage: release
  script:
    - semantic-release --debug --dry-run --no-ci --extends @enttribe/semantic-release-config
  rules:
    - if: $CI_DEFAULT_BRANCH == $CI_COMMIT_BRANCH

...
