---

stages:
  - release

.semantic-release:
  image: $CI_REGISTRY/semantic-release:1.0.0
  stage: release
  script:
    - semantic-release
  rules:
    - if: $CI_DEFAULT_BRANCH == $CI_COMMIT_BRANCH

...
