---

include: gitlab-http-access.gitlab-ci.yml

# Use this job template to provide automated samentic version tags and gitlab releases
# for you projects
#
# Use this job template by including this file from the project
# and defining the release stage
#
# eg.:
# include:
#   - project: automation/cicd/templates
#     version: ${latest project release version}
#     file: semantic-release.gitlab-ci.yml  
# stages:
#   - release

semantic-release:
  variables:
    SEMANTIC_RELEASE_USER: semantic-release-bot
    SEMANTIC_RELEASE_AUTH: ${SEMANTICRELEASE_TOKEN}
    GITLAB_USERNAME: ${SEMANTIC_RELEASE_USER}
    GITLAB_USERAUTH: ${SEMANTIC_RELEASE_AUTH}
  extends:
    - .gitlab_http_access
  image: $REGISTRY/semantic-release:v1.3.4@sha256:601997f251627c15fd839023372bed3e4932197743b4f16d158e0c4f8ec4a61a
  stage: release
  script:
    - GL_TOKEN=${SEMANTICRELEASE_TOKEN} semantic-release --extends @enttribe/semantic-release-config --repository-url "${GITLAB_AUTHENTICATED_REPO_URL}"
  rules:
    - if: $CI_DEFAULT_BRANCH == $CI_COMMIT_BRANCH

...
