---

maven-snapshots-check:
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "master"
    - if: $CI_COMMIT_BRANCH != null && $CI_COMMIT_BRANCH == "master"
    - if: $CI_COMMIT_TAG != null
  script:
    - (! grep SNAPSHOT $PROJECT_ROOT/pom.xml)

...