---

# This job template defines the correct way of using docker dind as a service
# This job template is ment to be included and extended as part of another job
# eg.:
#  include:
#    - project: automation/cicd/templates
#      ref: ${project latest version}
#      file: services/docker-dind.gitlab-ci.yml
#  job1:
#    extends: .docker-dind
#    script:
#      - /bin/true
# OR
#   include: ...
#   job2:
#     services:
#       - some_service
#       - !reference [.docker-dind, services]

variables:
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  DOCKER_DAEMON_OPTIONS: "--tls=false --insecure-registry=${REGISTRY} --insecure-registry=${REGISTRY_PROXY} --insecure-registry=${REGISTRY_GROUP} --registry-mirror=http://${REGISTRY_GROUP} --ipv6 --fixed-cidr-v6 fd0f:dead:beef::/48 --bip 172.31.0.1/16 --default-address-pool base=172.30.0.0/16,size=24 --default-address-pool base=fd0e:dead:beef::/64,size=80 --dns 192.168.229.49 --dns 192.168.230.49 --dns 2a02:1800:100::100:1 --dns 2a02:1800:100::100:2 --dns 195.130.130.12 --dns 195.130.131.12 --dns-search inet.telenet.be --dns-search telenet-ops.be --default-ulimit nofile=65535:65535"

.docker-dind:
  services:
    - name: docker:dind
      entrypoint: ["sh", "-c", "dockerd-entrypoint.sh $DOCKER_DAEMON_OPTIONS"]

...
