---
include:
  - local: jobs/releasing/maven.gitlab-ci.yml

release-maven-hotfix-jgitver:
  extends: .release-maven
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^hotfix\/.*/
      exists:
        - "**/.mvn/jgitver.config.xml"
      when: manual
      allow_failure: true
    - when: never
  script:
    - (! grep SNAPSHOT $PROJECT_ROOT/pom.xml)
    - echo "SHORT_VERSION:" ${SHORT_VERSION}
    - git fetch --all
    - git checkout $CI_COMMIT_BRANCH
    - git tag -a ${SHORT_VERSION} -m "Release ${SHORT_VERSION}"
    - git push origin --tags
...