---

# This pipeline template is intended to be referenced as an include in a project
# which incorporates any form of ansible (role, collection, project, ...)
# eg:
# include:
#   - project: automation/cicd/templates
#     ref: ${latest project version}
#     file: pipelines/ansible.gitlab-ci.yml

include:
  - local: /pipelines/recommended-test-jobs.gitlab-ci.yml
  - local: /jobs/testing/ansible/ansible-lint.gitlab-ci.yml
  - local: /jobs/testing/ansible/ansible-molecule.gitlab-ci.yml
  - local: /jobs/testing/ansible/ansible-test.gitlab-ci.yml
  - local: /jobs/releasing/semantic-release.gitlab-ci.yml

stages:
  - test
  - integration
  - release

sonarqube:
  allow_failure: true
  variables:
    SONAR_PROJECT_TAGS: ansible
  rules:
    # Do not run on tags
    - if: $CI_COMMIT_TAG
      when: never
    # Run on MR's
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    # Run on default branch
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    # Run on any other branch
    - if: $CI_COMMIT_BRANCH
    # do not run otherwise
    - when: never
  needs:
    - job: ansible-coverage
      artifacts: true
      optional: true

semantic-release:
  rules:
    # Run on default branch
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    # Do not run otherwise
    - when: never

...
