---

# Use this job template to destroy a cdk stack
#
# required input:
# - AWS_ACCOUNT_NAME: the name of the AWS account to destroy the stack
# - AWS_ACCOUNT: the AWS account number
# - AWS_ASSUME_ROLE_FOR_DEPLOY: the role to assume to destroy the stack
# - CUSTOMIZE_PREFIX_FOR_BRANCHES: if the branch name should be customized
# env
# This job requires the user to include this job template
# This job requires the user to define the build stage in his pipeline
# eg:
# include:
#   - project: automation/cicd/templates
#     ref: ${latest project version}
#     file: jobs/building/maven.gitlab-ci.yml
# stages:
#   - build

include:
  - local: jobs/utils/aws/aws-assume-role.gitlab-ci.yml
  - local: jobs/utils/create-config-for-stage.yml

cdk-destroy:
  extends: .aws_assume_role
  stage: destroy
  variables:
    ARS_AWS_PROFILE: "$AWS_ACCOUNT_NAME"
    ARS_AWS_ROLE_TO_ASSUME: "arn:aws:iam::$AWS_ACCOUNT:role/$AWS_ASSUME_ROLE_FOR_DEPLOY"
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CUSTOMIZE_PREFIX_FOR_BRANCHES && $CUSTOMIZE_PREFIX_FOR_BRANCHES == "True" && $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /^renovate/
      when: delayed
      start_in: 15 minutes
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CUSTOMIZE_PREFIX_FOR_BRANCHES && $CUSTOMIZE_PREFIX_FOR_BRANCHES == "True" && $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME !~ /^renovate/
  before_script:
    - !reference [.aws_assume_role, before_script]
    - !reference [.create-config-for-stage]
  script: 
    - cdk destroy --all --force
  retry: 2
  when: manual
  allow_failure: false
  resource_group: destroy

...
