---

include: 
  - local: /jobs/utils/awx.gitlab-ci.yml

# This job template can be used to deploy a 'yelo-framework' (war) or 'tvbuild-framework' (jar) style java application
#
# This job template is meant to be included via extention, but only variables should be defined
# eg.:
#  include:
#    - project: automation/cicd/templates
#      ref: ${project latest version}
#      file: jobs/deploying/awx-java-application.gitlab-ci.yml
#  stages:
#    - deploy
#  job1:
#    extends:
#      - .awx-java-application-deploy
#    variables:
#      TELENET_ENV: edp
#
#      TODO

.awx-java-application-deploy:
  stage: deploy
  variables:
    TELENET_ENV: ''
    TELENET_SQUAD: ''
    APPLICATION_NAME: ''
    APPLICATION_PACKAGING: 'jar'
  extends:
    - .awx-job
  before_script:
    - echo "TODO: version, packaging, branch and template detections"
    - AWX_EXTRA_VARS="{\"app\": \"$APPLICATION_NAME\", \"applications\": {\"$APPLICATION_NAME\": {\"version\": \"$VERSION\"}}}"
    - !reference [.awx-job, before_script]

...
