---

# Use this job template deploy to EKS
#
# env
# This job requires the user to include this job template
# This job requires the user to define the deploy stage in his pipeline
# eg:
# include:
#   - project: automation/cicd/templates
#     ref: ${latest project version}
#     file: jobs/deploying/update-deploy-helm-charts.gitlab-ci.yml
# stages:
#   - deploy

.update-deploy-helm-charts:
  image: registry.dev.yelo.inet.telenet.be/enttribe/kube-tools:1.0.0
  stage: deploy
  variables:
    CONFIG_PATH: ""
    CONFIG_BRANCH: ""
  before_script:
    - git clone --branch ${CONFIG_BRANCH} "http://gitlab-access-token:${CONFIG_ACCESS_TOKEN}@${CI_SERVER_HOST}/${CONFIG_PATH}" --single-branch
    - cd eks-deployment-config
    - cd applications
  script:
    - if [ -n "$CI_COMMIT_SHORT_SHA" ]; then
    -   yq -iy ".applications.\"$CI_PROJECT_NAME\".ecr.imageTag=$CI_COMMIT_SHORT_SHA" values-dev.yaml
    - fi
    - if [ -n "$HELM_REVISION" ]; then
    -   yq -iy ".applications.\"$CI_PROJECT_NAME\".helm.targetRevision=$HELM_REVISION" values-dev.yaml
    - fi
    - git config user.email "$GITLAB_USER_EMAIL"
    - git config user.name "$GITLAB_USER_NAME"
    - git commit -am "Update $CI_PROJECT_NAME to $CI_COMMIT_SHORT_SHA on EDP" || true
    - git push || true
    - echo "Completed deployment of $CI_PROJECT_NAME version $CI_COMMIT_SHORT_SHA EDP"

...
