---

include:
  - local: jobs/building/containers/kaniko-ecr.gitlab-ci.yml

publish-maven-ecr-image:
  stage: publish
  extends: .kaniko_ecr
  variables:
    ARS_AWS_PROFILE: "$AWS_SHARED_ACCOUNT_NAME"
    ARS_AWS_ROLE_TO_ASSUME: "arn:aws:iam::$AWS_SHARED_ACCOUNT:role/$AWS_ASSUME_ROLE_FOR_ECR_DEPLOY"
    KANIKO_CONTEXT: "$PROJECT_ROOT"
  needs:
    - job: maven-build
      artifacts: true
    - job: maven-create-jar
      artifacts: true
  script:
    - ${KANIKO_COMMAND} --dockerfile Dockerfile --destination $ECR_REGISTRY/$CI_PROJECT_NAME:$BUILD_VERSION --destination $ECR_REGISTRY/$CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA

...
