---

include:
  - local: jobs/building/containers/kaniko.gitlab-ci.yml
  - local: jobs/utils/aws/aws-ecr-login.gitlab-ci.yml

# This job template can be used to build containers from Dockerfiles using kaniko and authenticate against ECR
#
# KANIKO_COMMAND should contain anything you need:
#   - proxy settings as build-arg's
#   - correct use of $REGISTRY and $REGISTRY_GROUP as required by our nexus setup
#   - --cache (caches intermediate build layers on docker registry, makes next builds faster most of the time)
#   - --reproducible (generates layers and containers with epoch 0 timestamps eg)
#   - build context set to project directory
#
# If any of these settings are not required, or require a different value please read the implementation carefully
# and use as much on the assignment to KANIKO_COMMAND as possible
#
# This job template is meant to be included and extended as part of another job
# eg.:
#  include:
#    - project: automation/cicd/templates
#      ref: ${project latest version}
#      file: jobs/building/containers/kaniko-ecr.gitlab-ci.yml
#  stages:
#    - build
#  variables:
#    ARS_AWS_PROFILE: "<team>-<aws env>"
#    ARS_AWS_ROLE_TO_ASSUME: "arn:aws:iam:<id>:role/<role_name>"
#  job1:
#    extends: .kaniko_ecr
#    script:
#      - ${KANIKO_COMMAND} --dockerfile Dockerfile --build-arg something=true --destination $REGISTRY/<namespace>/<container_id>:<tag>

.kaniko_ecr:
  extends:
    - .aws_ecr_login
  stage: build
  image:
    name: $REGISTRY/automation/containers/kaniko-curl
    entrypoint: [""]
  variables:
    KANIKO_CONTEXT: "${CI_PROJECT_DIR}"
  before_script:
    - !reference [.aws_ecr_login, before_script]
    - |-
       mkdir -p /kaniko/.docker
       KANIKOPROXYBUILDARGS=""
       KANIKOCFG="{ \"auths\":{\"${ECR_REGISTRY}\":{\"username\":\"${ECR_USERNAME}\",\"password\":\"${ECR_PASSWORD}\"}}"
       if [ "x${HTTP_PROXY}" != "x" -o "x${HTTPS_PROXY}" != "x" ]; then
         KANIKOCFG="${KANIKOCFG}, \"proxies\": { \"default\": { \"httpProxy\": \"${HTTP_PROXY}\", \"httpsProxy\": \"${HTTPS_PROXY}\", \"noProxy\": \"${NO_PROXY}\"}}"
         KANIKOPROXYBUILDARGS="${KANIKOPROXYBUILDARGS} --build-arg http_proxy=${HTTP_PROXY} --build-arg https_proxy=${HTTPS_PROXY} --build-arg no_proxy=${NO_PROXY}"
       fi
       KANIKOCFG="${KANIKOCFG} }"
       echo "${KANIKOCFG}" > /kaniko/.docker/config.json
       KANIKO_COMMAND="/kaniko/executor --reproducible --insecure --insecure-pull --registry-mirror ${REGISTRY_GROUP} --context ${KANIKO_CONTEXT} ${KANIKOPROXYBUILDARGS} --cache=true"

...
