---
.set-git-credentials:
  before_script:
    - export CI_SERVER_HOST=${AWS_CI_SERVER_HOST:-$CI_SERVER_HOST}
    - git config --global credential.http://$CI_SERVER_HOST.username gitlab-ci-token
    - git config --global credential.helper 'store --file /.gitcredentials'
    - echo -n "http://gitlab-ci-token:${DEPLOY_TOKEN}@$CI_SERVER_HOST" > /.gitcredentials
    - git config --global credential.https://$CI_SERVER_HOST.username gitlab-ci-token
    - echo -n "https://gitlab-ci-token:${DEPLOY_TOKEN}@$CI_SERVER_HOST" > /.gitcredentials
    - 'if [ -z "$AWS_CI_SERVER_HOST" ]; then export SCHEME="http"; else export SCHEME="https"; fi'
    - git remote set-url origin "${SCHEME}://gitlab-ci-token:${DEPLOY_TOKEN}@$CI_SERVER_HOST/$CI_PROJECT_PATH.git"
    - git config user.email "gitlab-runner@telenetgroup.be"
    - git config user.name "Gitlab Runner (AWX-IT User)"
...